<?php

/**
 * BaseSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $currency
 * @property boolean $active
 * @property string $comment
 * @property string $message
 * @property Doctrine_Collection $Participants
 * @property Doctrine_Collection $Auctions
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getCurrency()     Returns the current record's "currency" value
 * @method boolean             getActive()       Returns the current record's "active" value
 * @method string              getComment()      Returns the current record's "comment" value
 * @method string              getMessage()      Returns the current record's "message" value
 * @method Doctrine_Collection getParticipants() Returns the current record's "Participants" collection
 * @method Doctrine_Collection getAuctions()     Returns the current record's "Auctions" collection
 * @method Session             setName()         Sets the current record's "name" value
 * @method Session             setCurrency()     Sets the current record's "currency" value
 * @method Session             setActive()       Sets the current record's "active" value
 * @method Session             setComment()      Sets the current record's "comment" value
 * @method Session             setMessage()      Sets the current record's "message" value
 * @method Session             setParticipants() Sets the current record's "Participants" collection
 * @method Session             setAuctions()     Sets the current record's "Auctions" collection
 * 
 * @package    bachelor
 * @subpackage model
 * @author     Florian Stallmann
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSession extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('session');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('currency', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('comment', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('message', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Participant as Participants', array(
             'local' => 'id',
             'foreign' => 'session_id'));

        $this->hasMany('Auction as Auctions', array(
             'local' => 'id',
             'foreign' => 'session_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}