<?php

/**
 * BaseParticipant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $session_id
 * @property string $ip
 * @property string $name
 * @property decimal $init_money
 * @property decimal $money
 * @property decimal $earned_money
 * @property Session $Session
 * @property Doctrine_Collection $Bidder
 * 
 * @method integer             getSessionId()    Returns the current record's "session_id" value
 * @method string              getIp()           Returns the current record's "ip" value
 * @method string              getName()         Returns the current record's "name" value
 * @method decimal             getInitMoney()    Returns the current record's "init_money" value
 * @method decimal             getMoney()        Returns the current record's "money" value
 * @method decimal             getEarnedMoney()  Returns the current record's "earned_money" value
 * @method Session             getSession()      Returns the current record's "Session" value
 * @method Doctrine_Collection getBidder()       Returns the current record's "Bidder" collection
 * @method Participant         setSessionId()    Sets the current record's "session_id" value
 * @method Participant         setIp()           Sets the current record's "ip" value
 * @method Participant         setName()         Sets the current record's "name" value
 * @method Participant         setInitMoney()    Sets the current record's "init_money" value
 * @method Participant         setMoney()        Sets the current record's "money" value
 * @method Participant         setEarnedMoney()  Sets the current record's "earned_money" value
 * @method Participant         setSession()      Sets the current record's "Session" value
 * @method Participant         setBidder()       Sets the current record's "Bidder" collection
 * 
 * @package    bachelor
 * @subpackage model
 * @author     Florian Stallmann
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParticipant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('participant');
        $this->hasColumn('session_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ip', 'string', 32, array(
             'type' => 'string',
             'unique' => true,
             'length' => 32,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('init_money', 'decimal', 10, array(
             'type' => 'decimal',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('money', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             ));
        $this->hasColumn('earned_money', 'decimal', 10, array(
             'type' => 'decimal',
             'notnull' => true,
             'default' => 0,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Session', array(
             'local' => 'session_id',
             'foreign' => 'id'));

        $this->hasMany('Bidder', array(
             'local' => 'id',
             'foreign' => 'participant_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}