<?php

/**
 * Bid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bachelor
 * @subpackage model
 * @author     Florian Stallmann
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Bid extends BaseBid
{
}
