<?php

/**
 * BidTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    bachelor
 * @subpackage model
 * @author     Florian Stallmann
 */
class BidTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     * @return BidTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bid');
    }
}