generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Bidder
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          bidder
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new:             { label: "Create a new auction" }
      fields:
        money_spent:      { help: "Sum of all bidding fees spent for this auction" }
      list:
        title:            Bidders per participant and auction
        display:          [=id, participant, auction, valuation, bid_fee]
        max_per_page:     10
        sort:             [id, desc]
      filter:
        display:          [auction_id, participant_id]
      form:
        display:
          NONE:           [auction_id, participant_id]
          "Settings":     [valuation, bid_fee]
          "Internal":     [money_spent, bot_active, direct_buy, direct_count, direct_price]
      edit:
        title:            Edit Bidder
      new:
        title:            New Bidder
